### ISSUE TITLE
Fails to parse python (problem using codemirror?)

### ISSUE THREAD

**Issue by brainstormtrooper** [salt42/blueprint#24]
Blueprint con't parse python - here's the error console output:

---

Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:481:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:405)
    at file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/main.js:361:3
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:291:33)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done](file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27220)
    at Object.d.always (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28096) /utils/DeprecationWarning.js:90
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:481:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:405)
    at file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/main.js:367:3
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:291:33)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done](file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27220)
    at Object.d.always (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:28096) /utils/DeprecationWarning.js:90
Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new _beforeHTMLReady.jQuery.fn.init (/brackets.js:481:36)
    at n (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:405)
    at Object.exports.update (file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/src/minimap.js:262:3)
    at parseDoc (file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/main.js:162:12)
    at Object.<anonymous> (file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/main.js:281:4)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done](file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27220)
    at changeDocument (file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/main.js:272:50)
    at file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/main.js:368:4 /utils/DeprecationWarning.js:90
Exception in 'currentFileChange' listener on 
Object
 TypeError: Cannot read property 'length' of undefined TypeError: Cannot read property 'length' of undefined
    at callback (file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/src/outlines/python.js:67:36)
    at update (file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/src/outlines/python.js:167:5)
    at Object.exports.update (file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/src/outlines/python.js:186:14)
    at forceUpdate (file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/src/outliner.js:197:17)
    at Object.exports.update (file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/src/outliner.js:281:10)
    at parseDoc (file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/main.js:159:18)
    at Object.<anonymous> (file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/main.js:281:4)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26911)
    at Object.k.add [as done](file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27220)
    at changeDocument (file:///home/rick/.config/Brackets/extensions/user/blueprint.outliner/main.js:272:50) 

---

hope that helps a bit...

**Comment by brainstormtrooper** [comment]
It works fine with PHP and I tested with no other extensions loaded.

Running on 64bit Linux (openSUSE)... if that makes a difference...

**Comment by ianchi** [comment]
I have the same problem. After switching to a Python document a get the same error, and then it also stops working for all kind of files. I need to restart Brackets to get it back working.
It is an excellent plugin it would be great to have it working also on .py files.

**Comment by salt42** [comment]
sry for the late reaction and thx for the fix @ianchi.
